language: objective-c
before_install:
    - brew install oclint.rb
script:
    - xcodebuild -workspace Framework/SparkFramework.xcworkspace -scheme SparkWebService build | tee xcodebuild.log
    - oclint-xcodebuild
    - oclint-json-compilation-database
notifications:
  email:
    - Valery_Demin@epam.com
