language: objective-c
env:
  matrix:
    - SPARK_SCHEME=SparkCore
    - SPARK_SCHEME=SparkLogger
    - SPARK_SCHEME=SparkObservation
    - SPARK_SCHEME=SparkSerialization
    - SPARK_SCHEME=SparkServices
    - SPARK_SCHEME=SparkWebService
    - SPARK_SCHEME=SparkAttributesCodeGenerator
before_install:
    - curl -O http://archives.oclint.org/releases/0.7/oclint-0.7-x86_64-apple-darwin-10.tar.gz
    - tar -zxvf oclint-0.7-x86_64-apple-darwin-10.tar.gz
    # =================     Remove necessary rules from "lib/oclint/rules/" folder of oclint     ===========
    #- rm $('pwd')/oclint-0.7-x86_64-apple-darwin-10/lib/oclint/rules/libUnusedMethodParameterRule.dylib
    # ======================================================================================================
    - OCLINT_HOME=$('pwd')/oclint-0.7-x86_64-apple-darwin-10
    - PATH=$OCLINT_HOME/bin:$PATH
before_script:
    - export WORKSPACE="-workspace Framework/SparkFramework.xcworkspace"
    - export PROJECT="-project tools/SparkAttributesCodeGenerator/SparkAttributesCodeGenerator.xcodeproj"
    - if [[ $SPARK_SCHEME == SparkAttributesCodeGenerator ]]; then export PATCH_FOR_PROJECT_OR_WORKSPACE=$PROJECT; else export PATCH_FOR_PROJECT_OR_WORKSPACE=$WORKSPACE; fi
script:
    - xcodebuild $PATCH_FOR_PROJECT_OR_WORKSPACE -scheme $SPARK_SCHEME build | tee xcodebuild.log > /dev/null
    - oclint-xcodebuild
    - oclint-json-compilation-database -- -rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 30 -max-priority-3 65
    - if [[ $SPARK_SCHEME != SparkAttributesCodeGenerator ]]; then xctool $WORKSPACE -scheme $SPARK_SCHEME test -sdk iphonesimulator; fi	
notifications:
  email:
    - Valery_Demin@epam.com