language: objective-c
before_install:
    - brew install oclint.rb
script:
    - xcodebuild -workspace Framework/SparkFramework.xcworkspace -scheme SparkWebService build | tee xcodebuild.log
    - echo xccodebuild.log
    - oclint-xcodebuild
    - echo compile_commands.json
    - oclint-json-compilation-database
notifications:
  email:
    - Valery_Demin@epam.com