language: objective-c
before_install:
    - brew install oclint.rb
script:
    - cd Framework
    - pwd
    - ls
    - which clang
    - clang --version
    - find /usr/ stdarg.h | grep stdarg.h
notifications:
  email:
    - Valery_Demin@epam.com