language: objective-c
env:
    - SPARK_SCHEME=SparkCore
    - SPARK_SCHEME=SparkLogger
    - SPARK_SCHEME=SparkObservation
    - SPARK_SCHEME=SparkSerialization
    - SPARK_SCHEME=SparkServices
    - SPARK_SCHEME=SparkWebService
before_install:
    - curl -O http://archives.oclint.org/releases/0.7/oclint-0.7-x86_64-apple-darwin-10.tar.gz
    - tar -zxvf oclint-0.7-x86_64-apple-darwin-10.tar.gz
    - rm $('pwd')/oclint-0.7-x86_64-apple-darwin-10/lib/oclint/rules/libUnusedMethodParameterRule.dylib	
    - OCLINT_HOME=$('pwd')/oclint-0.7-x86_64-apple-darwin-10
    - PATH=$OCLINT_HOME/bin:$PATH
script:
    # =================     Spark Schemes     =================
    - xcodebuild -workspace Framework/SparkFramework.xcworkspace -scheme $SPARK_SCHEME build | tee xcodebuild.log > /dev/null
    - oclint-xcodebuild
    - oclint-json-compilation-database -- -rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 20 -max-priority-3 65
    - xctool -workspace Framework/SparkFramework.xcworkspace -scheme $SPARK_SCHEME test -sdk iphonesimulator
    # =================     SparkAttributesCodeGenerator     =================
    - xcodebuild -project tools/SparkAttributesCodeGenerator/SparkAttributesCodeGenerator.xcodeproj -scheme SparkAttributesCodeGenerator build | tee xcodebuild.log > /dev/null
    - oclint-xcodebuild
    - oclint-json-compilation-database -- -rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 20 -max-priority-3 65
notifications:
  email:
    - Valery_Demin@epam.com