language: objective-c
before_install:
    - brew install oclint.rb
script:
    - xcodebuild -workspace Framework/SparkFramework.xcworkspace -scheme SparkCore build | tee xcodebuild.log
    - cat xcodebuild.log
    - oclint-xcodebuild
    - cat compile_commands.json
    - oclint-json-compilation-database
notifications:
  email:
    - Valery_Demin@epam.com