language: objective-c
script:
    - xctool -workspace Framework/SparkFramework.xcworkspace -scheme SparkWebService build | tee xcodebuild.log
	- oclint-xcodebuild
	- oclint-json-compilation-database
notifications:
  email:
    - Valery_Demin@epam.com
