language: objective-c

env:
    - SPARK_SCHEME=Simian
    - SPARK_SCHEME=ROADCore
    - SPARK_SCHEME=ROADLogger
    - SPARK_SCHEME=ROADServices
    - SPARK_SCHEME=ROADWebService
    - SPARK_SCHEME=ROADObservation
    - SPARK_SCHEME=ROADSerialization
    - SPARK_SCHEME=ROADAttributesCodeGenerator

before_script:
    - chmod +x ./script_simian.sh
    - chmod +x ./script_general.sh
    - chmod +x ./coveralls.rb

script:
    - if [[ $SPARK_SCHEME == Simian ]]; then ./script_simian.sh; else ./script_general.sh; fi

after_success:
    - if [[ $SPARK_SCHEME != Simian && $SPARK_SCHEME != ROADAttributesCodeGenerator ]]; then ./coveralls.rb --extension m; fi

notifications:
  email:
    - Nikita_Leonov@epam.com
    - Yuru_Taustahuzau@epam.com
    - Eduard_Beleninik@epam.com
    - Igor_Chesnokov@epam.com
    - Oleh_Sannikov@epam.com
    - Tymur_Mamedov@epam.com
    - Valery_Demin@epam.com