language: objective-c
before_install:
    - curl -O http://archives.oclint.org/releases/0.7/oclint-0.7-x86_64-apple-darwin-10.tar.gz
    - tar -zxvf oclint-0.7-x86_64-apple-darwin-10.tar.gz
    - OCLINT_HOME=$('pwd')/oclint-0.7-x86_64-apple-darwin-10
    - PATH=$OCLINT_HOME/bin:$PATH
script:
    - alias analize="oclint-json-compilation-database -- -rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 20 -max-priority-3 65"
    - alias params="-- -rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 20 -max-priority-3 65"
    - alias params2="-rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 20 -max-priority-3 65"
    # =================     SparkCore     =================
    - xcodebuild -workspace Framework/SparkFramework.xcworkspace -scheme SparkCore build | tee xcodebuild.log > /dev/null
    - oclint-xcodebuild
    - analize
    - oclint-json-compilation-database params
    - oclint-json-compilation-database params2
notifications:
  email:
    - Valery_Demin@epam.com