language: objective-c

env:
    - SPARK_SCHEME=Simian
    - SPARK_SCHEME=SparkCore
    - SPARK_SCHEME=SparkLogger
    - SPARK_SCHEME=SparkServices
    - SPARK_SCHEME=SparkWebService
    - SPARK_SCHEME=SparkObservation
    - SPARK_SCHEME=SparkSerialization
    - SPARK_SCHEME=SparkAttributesCodeGenerator

before_script:
    - chmod +x ./install_simian.sh
    - chmod +x ./install_oclint.sh
    - chmod +x ./script_simian.sh
    - chmod +x ./script_general.sh

script:
    - if [[ $SPARK_SCHEME == Simian ]]; then ./install_simian.sh > /dev/null; else ./install_oclint.sh > /dev/null; fi
    - if [[ $SPARK_SCHEME == Simian ]]; then ./script_simian.sh; else ./script_general.sh; fi

notifications:
  email:
    - Valery_Demin@epam.com